### ISSUE TITLE
Adding GDG Nicosia as Partner

### ISSUE THREAD

**Issue by adilshehzad786** [CNCF-Lahore/CNCF-Lahore.github.io#25]
@zaidbari  can you please provide your chapter logo

**Comment by zaidbari** [comment]
![Artboard 6 copy@4x](https://github.com/CNCF-Lahore/CNCF-Lahore.github.io/assets/29076354/1e93fa69-7021-456b-8e56-05ebe762fe1a)

**Comment by zaidbari** [comment]
Send me the CNCF or KCD logo for GDG website as well.

**Comment by adilshehzad786** [comment]
@moezmustafa  can you share KCD logo with @zaidbari ?

**Comment by adilshehzad786** [comment]
@muhammadbilal10  can you please add GDG Nicosia logo to the kcdlahore website , you can replace it with softec logo.

**Comment by adilshehzad786** [comment]
Closing this issue,  since it is inactive or completed from both end
